export default [
  {
    files: ["**/*.js"],
    languageOptions: {
      ecmaVersion: 2020,
      sourceType: "script",
      globals: {
        window: "readonly",
        document: "readonly",
        navigator: "readonly",
        console: "readonly",
        localStorage: "readonly",
        setTimeout: "readonly",
        setInterval: "readonly",
        clearTimeout: "readonly",
        clearInterval: "readonly",
        fetch: "readonly",
        Promise: "readonly",
        Date: "readonly",
        JSON: "readonly",
        Array: "readonly",
        Object: "readonly",
        Math: "readonly",
        Notification: "readonly",
        firebase: "readonly",
        L: "readonly",
        itinerario: "readonly",
        regioni: "readonly",
        TRIP_COORDS: "readonly",
        POI_ATTIVITA: "readonly",
        DAYS_DATA: "readonly",
        WIKI_LINKS: "readonly",
        WIKI_COUNTRIES: "readonly",
        WIKI_TREKS: "readonly",
        WIKI_FOOD: "readonly",
        WIKI_PEOPLE: "readonly",
        WIKI_PARKS: "readonly",
        OWNER_UIDS: "readonly",
        FAMILY_ID: "writable",
        isOwner: "writable",
        isEN: "readonly",
        LANG: "readonly",
        KEYS: "readonly",
        COUNTRY_LABELS: "readonly"
      }
    },
    rules: {
      "no-undef": "warn",
      "no-unused-vars": "off",
      "no-redeclare": "warn",
      "no-unreachable": "error",
      "no-constant-condition": "warn",
      "no-dupe-keys": "error",
      "no-duplicate-case": "error",
      "no-extra-semi": "warn",
      "no-func-assign": "error",
      "no-inner-declarations": "warn",
      "no-irregular-whitespace": "warn",
      "use-isnan": "error",
      "valid-typeof": "error",
      "no-cond-assign": "warn",
      "eqeqeq": "off",
      "no-empty": "warn"
    }
  }
];
